import type { Metadata } from "next";
import { Manrope, Playfair_Display } from "next/font/google";
import "./globals.css";

const font = Manrope({
  variable: "--font",
  subsets: ["latin"],
});

const subfont = Playfair_Display({
  variable: "--font-sub",
  subsets: ["latin"],
  style: ["italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.variable} ${subfont.variable} antialiased bg-[#F4F6FB]`}
      >
        {children}
        <div className="mt-[100px]"></div>
      </body>
    </html>
  );
}
